name: torch11
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch
  - cudatoolkit=11.3
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - scikit-image
  - tensorflow
  - opencv
  - pillow
  - pyyaml
  - jupyterlab
  - ipython
  - tqdm
  - h5py
  - pip:
    - torchmetrics
    - torchtext
    - transformers
    - fastai
    - matplotlib-venn
    - plotly
    - wandb
    - altair
    - seaborn
    - statsmodels
    - sympy
    - networkx
    - spacy
    - spacy-transformers
    - plotnine
    - scipy
    - tensorflow-hub
    - tensorflow-datasets
    - imageio
    - tqdm
    - fasttext
    - gitpython
    - pandas-profiling
    - kaleido
    - lightgbm
    - xgboost
    - pycaret
    - shap
    - catboost
    - optuna
    - loguru
    - pyod
    - jupyter
    - dash
    - jupyter-notebook
    - plotly
    - geopandas
    - folium
    - ipywidgets
    - streamlit
    - pillow-simd
    - pyautogui
    - pyspark
    - lightkurve
    - statsmodels
    - fastapi
    - pyarrow
    - graphviz
    - sqlalchemy
    - kivy
    - textblob
    - nltk
    - gensim
    - google-cloud
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-cloud-storage
    - google-cloud-bigquery
    - google-cloud-firestore
    - google-cloud-pubsub
    - google-cloud-speech
    - google-cloud-vision
    - google-cloud-language
    - google-cloud-translate
    - google-cloud-logging
    - google-cloud-dataproc
    - google-cloud-datalab
    - google-cloud-dataprep
    - google-cloud-datastore
    - google-cloud-logging
    - google-cloud-sql
    - gcloud
    - gspread
    - google-cloud-notebooks
    - gmap
    - pyjwt
    - boto3
    - azure
    - flask
    - requests
    - requests_oauthlib
    - opencv-python-headless
